const MAX_PAYLOAD_BYTES = 2 * 1024 * 1024 // 2 MB

export default defineEventHandler(async (event) => {
  const config = useRuntimeConfig()
  const githubToken = config.githubToken as string
  if (!githubToken) {
    throw createError({ statusCode: 500, message: 'Bug reporting not configured' })
  }

  // Size guard — screenshots can be large
  const contentLength = Number(getHeader(event, 'content-length') || 0)
  if (contentLength > MAX_PAYLOAD_BYTES) {
    throw createError({ statusCode: 413, message: 'Payload too large' })
  }

  const body = await readBody<{
    description: string
    pageUrl: string
    screenshot: string
    pageState: Record<string, unknown>
    environment: Record<string, unknown>
  }>(event)

  if (!body.description?.trim()) {
    throw createError({ statusCode: 400, message: 'Description is required' })
  }

  const repo = config.githubRepo as string || 'instarea-sk/google-contacts-refiner'
  const session = await getUserSession(event)
  const reporter = session?.user?.name || session?.user?.email || 'Anonymous (demo)'

  // Build screenshot markdown — embed as base64 data URL in a <details> block
  // GitHub renders base64 images in issue bodies up to ~2 MB
  let screenshotMarkdown = ''
  if (body.screenshot) {
    const base64 = body.screenshot.startsWith('data:')
      ? body.screenshot
      : `data:image/png;base64,${body.screenshot}`
    screenshotMarkdown = [
      '## Screenshot',
      `<details><summary>Click to view screenshot</summary>`,
      '',
      `<img src="${base64}" width="100%" />`,
      '',
      '</details>',
    ].join('\n')
  }

  // Build the issue body optimized for Claude Code to reproduce and fix
  const pagePath = body.pageUrl?.replace(/^https?:\/\/[^/]+/, '') || '/unknown'
  const pageFiles = mapPageToFile(pagePath)
  const now = new Date().toISOString().slice(0, 19).replace('T', ' ')

  const issueBody = [
    '## Bug Report',
    `**Page**: \`${pagePath}\``,
    `**Reporter**: ${reporter}`,
    `**Date**: ${now}`,
    '',
    '## What happened',
    body.description.trim(),
    '',
    screenshotMarkdown,
    '',
    '## Environment',
    '```json',
    JSON.stringify(body.environment || {}, null, 2),
    '```',
    '',
    '## Page State',
    '```json',
    JSON.stringify(body.pageState || {}, null, 2),
    '```',
    '',
    '## Reproduction',
    `1. Navigate to \`${pagePath}\``,
    body.pageState && Object.keys(body.pageState).length > 0
      ? '2. Page state at time of report: see JSON above'
      : '',
    '',
    '## Files to Investigate',
    ...pageFiles.map(f => `- \`${f}\``),
    '',
    '---',
    '*Auto-generated by Contact Refiner bug reporter*',
  ].filter(Boolean).join('\n')

  // Create GitHub issue — wrap in try/catch to avoid leaking internal details
  let issueRes: { number: number, html_url: string }
  try {
    issueRes = await $fetch<{ number: number, html_url: string }>(
      `https://api.github.com/repos/${repo}/issues`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: 'application/vnd.github.v3+json',
        },
        body: {
          title: `[Bug] ${pagePath}: ${body.description.trim().slice(0, 80)}`,
          body: issueBody,
          labels: ['bug', 'user-reported'],
        },
      },
    )
  }
  catch (err: unknown) {
    console.error('GitHub issue creation failed:', err instanceof Error ? err.message : err)
    throw createError({ statusCode: 502, message: 'Bug report could not be submitted' })
  }

  return {
    issueNumber: issueRes.number,
    issueUrl: issueRes.html_url,
  }
})

/**
 * Map a dashboard page path to the likely source files for investigation.
 */
function mapPageToFile(path: string): string[] {
  const base = path.split('?')[0].replace(/\/$/, '') || '/dashboard'
  const pageName = base.slice(1) || 'index'

  const files = [
    `dashboard/app/pages/${pageName}.vue`,
  ]

  const apiMap: Record<string, string[]> = {
    'dashboard': ['dashboard/server/api/status.get.ts'],
    'review': ['dashboard/server/api/review/index.get.ts', 'dashboard/server/api/review/decide.post.ts'],
    'changelog': ['dashboard/server/api/changelog.get.ts'],
    'analytics': ['dashboard/server/api/analytics.get.ts'],
    'social-signals': ['dashboard/server/api/social-signals.get.ts'],
    'followup': ['dashboard/server/api/followup-scores.get.ts'],
    'runs': ['dashboard/server/api/pipeline-runs.get.ts'],
    'config': ['dashboard/server/api/config/index.get.ts'],
    'pipeline': [],
  }

  files.push(...(apiMap[pageName] || []))
  return files
}
